# typed: false
# frozen_string_literal: true

# Generated by the meshcore-cz/hopback release workflow. Do not edit by hand.
class HopbackAgent < Formula
  desc "Hopback MeshCore radio bridge agent"
  homepage "https://github.com/meshcore-cz/hopback"
  version "0.9.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/meshcore-cz/hopback/releases/download/v0.9.2/hopback-agent_v0.9.2_darwin_arm64.tar.gz"
      sha256 "08d65170bc16948f7f3d2082c4ddc6c9ded6ba6960b55757b54892c2bc9dcbb8"
    end
    on_intel do
      url "https://github.com/meshcore-cz/hopback/releases/download/v0.9.2/hopback-agent_v0.9.2_darwin_amd64.tar.gz"
      sha256 "1da24c41a346e6990d4bbd5548dad5e978a540c27663e222bd33ed438c728a9d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/meshcore-cz/hopback/releases/download/v0.9.2/hopback-agent_v0.9.2_linux_arm64.tar.gz"
      sha256 "f44e270a1d856a49dd562cb1ab5379794411017f893466c299423553334857b6"
    end
    on_intel do
      url "https://github.com/meshcore-cz/hopback/releases/download/v0.9.2/hopback-agent_v0.9.2_linux_amd64.tar.gz"
      sha256 "71cc63ab13df7b5160cb1b613f28fcdc2ed8008d904f9bccc717d6d0e43d29e3"
    end
  end

  def install
    bin.install "hopback-agent"
  end

  test do
    assert_path_exists bin/"hopback-agent"
  end
end
