# typed: false
# frozen_string_literal: true

# Generated by the meshcore-cz/hopback release workflow. Do not edit by hand.
class Hopbackd < Formula
  desc "Hopback MeshCore diagnostic web backend"
  homepage "https://github.com/meshcore-cz/hopback"
  version "0.9.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/meshcore-cz/hopback/releases/download/v0.9.2/hopbackd_v0.9.2_darwin_arm64.tar.gz"
      sha256 "3547566fe78ea912b88fb0a2d8a2f4c3c00260ac3f63cb601e094fc3ef30d98d"
    end
    on_intel do
      url "https://github.com/meshcore-cz/hopback/releases/download/v0.9.2/hopbackd_v0.9.2_darwin_amd64.tar.gz"
      sha256 "dc83d430c5fb3276f25c7de9aba89fb404bc7ebb933d4c9e37d4b6e46a18ea03"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/meshcore-cz/hopback/releases/download/v0.9.2/hopbackd_v0.9.2_linux_arm64.tar.gz"
      sha256 "4dfba0eeab728934c6fcad184b890182e77194c944382508b69c9fd8d6aec405"
    end
    on_intel do
      url "https://github.com/meshcore-cz/hopback/releases/download/v0.9.2/hopbackd_v0.9.2_linux_amd64.tar.gz"
      sha256 "0e946fc1c7ebe7fb9111636ae4a528c20753a78e25b6a6300610de1ffed79328"
    end
  end

  def install
    bin.install "hopbackd"
  end

  test do
    assert_path_exists bin/"hopbackd"
  end
end
