# typed: false
# frozen_string_literal: true

# Generated by the meshcore-cz/hopback release workflow. Do not edit by hand.
class HopbackAgent < Formula
  desc "Hopback MeshCore radio bridge agent"
  homepage "https://github.com/meshcore-cz/hopback"
  version "0.9.4"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/meshcore-cz/hopback/releases/download/v0.9.4/hopback-agent_v0.9.4_darwin_arm64.tar.gz"
      sha256 "34235e7831c49d2d250c45dd824081c80a2c70fb1cabddf41feafd4a862d11c5"
    end
    on_intel do
      url "https://github.com/meshcore-cz/hopback/releases/download/v0.9.4/hopback-agent_v0.9.4_darwin_amd64.tar.gz"
      sha256 "6453671c9f8f4c14338b8868a5a42065d79b575cb1b3b83d73b2ff6e20217998"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/meshcore-cz/hopback/releases/download/v0.9.4/hopback-agent_v0.9.4_linux_arm64.tar.gz"
      sha256 "91449ff04fb8cf35dd1ae208ef7d6dd016dea29ac07e755fa21fa6b4f0b637ed"
    end
    on_intel do
      url "https://github.com/meshcore-cz/hopback/releases/download/v0.9.4/hopback-agent_v0.9.4_linux_amd64.tar.gz"
      sha256 "150421b2bc871d23243dcd6d1b0143b40c9a87dbf2ce86c0be87301cf27bbda9"
    end
  end

  def install
    bin.install "hopback-agent"
  end

  test do
    assert_path_exists bin/"hopback-agent"
  end
end
