# typed: false
# frozen_string_literal: true

# Generated by the meshcore-cz/hopback release workflow. Do not edit by hand.
class Hopbackd < Formula
  desc "Hopback MeshCore diagnostic web backend"
  homepage "https://github.com/meshcore-cz/hopback"
  version "0.9.3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/meshcore-cz/hopback/releases/download/v0.9.3/hopbackd_v0.9.3_darwin_arm64.tar.gz"
      sha256 "d3c1e351898f6a1bddb4732fb354ca44b6b3bd68eef19923432001cb30d0543d"
    end
    on_intel do
      url "https://github.com/meshcore-cz/hopback/releases/download/v0.9.3/hopbackd_v0.9.3_darwin_amd64.tar.gz"
      sha256 "b7345c99561fb728460ff4e1e90879b7ba33ed7321c8ca31a1cf91681174de68"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/meshcore-cz/hopback/releases/download/v0.9.3/hopbackd_v0.9.3_linux_arm64.tar.gz"
      sha256 "ca1eafb6f7766c613d8256bf06f5988298f9cf0fc7c1b90ac09f258a80ff6211"
    end
    on_intel do
      url "https://github.com/meshcore-cz/hopback/releases/download/v0.9.3/hopbackd_v0.9.3_linux_amd64.tar.gz"
      sha256 "f104c9f4310f7052d0738361a03eef4a116f41de070230034cb3b3e64604a607"
    end
  end

  def install
    bin.install "hopbackd"
  end

  test do
    assert_path_exists bin/"hopbackd"
  end
end
