# typed: false
# frozen_string_literal: true

# Generated by the meshcore-cz/hopback release workflow. Do not edit by hand.
class HopbackAgent < Formula
  desc "Hopback MeshCore radio bridge agent"
  homepage "https://github.com/meshcore-cz/hopback"
  version "0.9.3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/meshcore-cz/hopback/releases/download/v0.9.3/hopback-agent_v0.9.3_darwin_arm64.tar.gz"
      sha256 "af8cc5c5c816dbf4f41171f5550b281651062f5d7961bf42e85dc4488aa9974b"
    end
    on_intel do
      url "https://github.com/meshcore-cz/hopback/releases/download/v0.9.3/hopback-agent_v0.9.3_darwin_amd64.tar.gz"
      sha256 "63fabf0897ea60ec83400253efd96273fb3a245f7346069dc535ed43c9ea7073"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/meshcore-cz/hopback/releases/download/v0.9.3/hopback-agent_v0.9.3_linux_arm64.tar.gz"
      sha256 "fb15d0df667f8cb278c3fc741f1a7e3ae26148e26507ff17f099ef4a5cc43726"
    end
    on_intel do
      url "https://github.com/meshcore-cz/hopback/releases/download/v0.9.3/hopback-agent_v0.9.3_linux_amd64.tar.gz"
      sha256 "bf58f71f045e8f1fd26a8d697a6b93531f29626840d49fd49e885ef4afc1a552"
    end
  end

  def install
    bin.install "hopback-agent"
  end

  test do
    assert_path_exists bin/"hopback-agent"
  end
end
