# typed: false
# frozen_string_literal: true

# Generated by the meshcore-cz/hopback release workflow. Do not edit by hand.
class Hopbackd < Formula
  desc "Hopback MeshCore diagnostic web backend"
  homepage "https://github.com/meshcore-cz/hopback"
  version "0.9.4"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/meshcore-cz/hopback/releases/download/v0.9.4/hopbackd_v0.9.4_darwin_arm64.tar.gz"
      sha256 "6316d5eeac155facd349d755bcdc8c8183f6a4a7fab618539355d688db3e4eeb"
    end
    on_intel do
      url "https://github.com/meshcore-cz/hopback/releases/download/v0.9.4/hopbackd_v0.9.4_darwin_amd64.tar.gz"
      sha256 "1b4a28011d2ec6641d698351e9ca674a9073410bba097ca1c7cfe3e0a8ce1748"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/meshcore-cz/hopback/releases/download/v0.9.4/hopbackd_v0.9.4_linux_arm64.tar.gz"
      sha256 "06b95ec7785559853cddca99fb28cfd7a6333dbb5bcdb3e54d15f5d41adb5c3a"
    end
    on_intel do
      url "https://github.com/meshcore-cz/hopback/releases/download/v0.9.4/hopbackd_v0.9.4_linux_amd64.tar.gz"
      sha256 "1a98e6c04460ba5a7cc62c8060d1b01868b05add20fb391efc65fb2c4c81e6c3"
    end
  end

  def install
    bin.install "hopbackd"
  end

  test do
    assert_path_exists bin/"hopbackd"
  end
end
