# typed: false
# frozen_string_literal: true

# Generated by the meshcore-cz/meshcore-go release workflow. Do not edit by hand.
class Mc < Formula
  desc "MeshCore terminal client"
  homepage "https://github.com/meshcore-cz/meshcore-go"
  version "0.5.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/meshcore-cz/meshcore-go/releases/download/v0.5.0/mc_v0.5.0_darwin_arm64.tar.gz"
      sha256 "37b022f253a1fd3289949aa78f6dcb74f75008bdb7d1d7d2350e66c13f20afc5"
    end
    on_intel do
      url "https://github.com/meshcore-cz/meshcore-go/releases/download/v0.5.0/mc_v0.5.0_darwin_amd64.tar.gz"
      sha256 "7275733fa23693ce00505f7bb2e4cf2401e728ebb13b516b874b07bab982515e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/meshcore-cz/meshcore-go/releases/download/v0.5.0/mc_v0.5.0_linux_arm64.tar.gz"
      sha256 "6ee55c59cd9bb80773311f4c79ba17511b1b9b452b1d66c5764504c2b78294a0"
    end
    on_intel do
      url "https://github.com/meshcore-cz/meshcore-go/releases/download/v0.5.0/mc_v0.5.0_linux_amd64.tar.gz"
      sha256 "5026c70b415a07fc739a1b4e985ade090110a55296d1df6fc9c01093011181d6"
    end
  end

  def install
    bin.install "mc"
  end

  test do
    system bin/"mc", "version"
  end
end
