#!/usr/bin/env bash
#
# Render a Homebrew formula for a prebuilt-binary release.
#
# Reads SHA256 sums from a SHA256SUMS file (the one attached to the release) and
# writes Formula/<FORMULA_NAME>.rb pointing at the four supported platform
# archives. Invoked by the meshcore-cz release workflows; can also be run by hand.
#
# Required env vars:
#   FORMULA_NAME    formula file/name, e.g. mc
#   CLASS           Ruby class name, e.g. Mc
#   BIN             installed binary name, e.g. mc
#   DESC            one-line description
#   REPO            owner/repo holding the release, e.g. meshcore-cz/meshcore-go
#   VERSION         release version without the leading v, e.g. 0.2.0
#   SUMS_FILE       path to a SHA256SUMS file containing the archive sums
# Optional:
#   ARCHIVE_PREFIX  archive name prefix (defaults to BIN)
#   OUT_DIR         output directory (defaults to Formula)
#   TEST_BODY       Ruby body for the formula's test block
set -euo pipefail

: "${FORMULA_NAME:?} ${CLASS:?} ${BIN:?} ${DESC:?} ${REPO:?} ${VERSION:?} ${SUMS_FILE:?}"
ARCHIVE_PREFIX="${ARCHIVE_PREFIX:-$BIN}"
OUT_DIR="${OUT_DIR:-Formula}"
TEST_BODY="${TEST_BODY:-assert_path_exists bin/\"$BIN\"}"

sha_for() {
  local file="$1" line
  # SHA256SUMS lines look like "<sha>  <file>" (sha256sum) or "<sha> *<file>".
  line="$(grep -E "[[:space:]][*]?${file//./\\.}\$" "$SUMS_FILE" | head -n1 || true)"
  [ -n "$line" ] || { echo "render-formula: no sha256 for $file in $SUMS_FILE" >&2; exit 1; }
  printf '%s' "${line%%[[:space:]]*}"
}

base="https://github.com/${REPO}/releases/download/v${VERSION}"
da="${ARCHIVE_PREFIX}_v${VERSION}_darwin_arm64.tar.gz"
di="${ARCHIVE_PREFIX}_v${VERSION}_darwin_amd64.tar.gz"
la="${ARCHIVE_PREFIX}_v${VERSION}_linux_arm64.tar.gz"
li="${ARCHIVE_PREFIX}_v${VERSION}_linux_amd64.tar.gz"

mkdir -p "$OUT_DIR"
cat > "${OUT_DIR}/${FORMULA_NAME}.rb" <<EOF
# typed: false
# frozen_string_literal: true

# Generated by the ${REPO} release workflow. Do not edit by hand.
class ${CLASS} < Formula
  desc "${DESC}"
  homepage "https://github.com/${REPO}"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "${base}/${da}"
      sha256 "$(sha_for "$da")"
    end
    on_intel do
      url "${base}/${di}"
      sha256 "$(sha_for "$di")"
    end
  end

  on_linux do
    on_arm do
      url "${base}/${la}"
      sha256 "$(sha_for "$la")"
    end
    on_intel do
      url "${base}/${li}"
      sha256 "$(sha_for "$li")"
    end
  end

  def install
    bin.install "${BIN}"
  end

  test do
    ${TEST_BODY}
  end
end
EOF

echo "render-formula: wrote ${OUT_DIR}/${FORMULA_NAME}.rb (v${VERSION})"
